# Generated by Django 6.0.4 on 2026-04-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_alter_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=254),
        ),
    ]
