# Generated by Django 6.0.4 on 2026-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carga_horario',
            field=models.IntegerField(default=0),
        ),
    ]
