# Generated by Django 6.0.4 on 2026-05-06 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_curso_carga_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
    ]
