# Generated by Django 6.0.4 on 2026-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
